const assert = require('node:assert/strict')
const fs = require('fs'), ts = require('typescript')
require.extensions['.ts'] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'), { compilerOptions:{ module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true } }).outputText, filename)
const display = require('../src/lib/tornadoDisplay.ts')
const state = require('../src/lib/explorerState.ts')
const f = (id,props={}) => ({type:'Feature',geometry:{type:'LineString',coordinates:[[-97,33],[-96,34]]},properties:{id,...props}})
const records=[f(2,{ef_rating:'3',event_date:'1973-09-25',state:'KS',path_length_km:10,distance_km:2,fatalities:0}),f(1,{ef_rating:'3',event_date:'1973-09-25',state:'KS',path_length_km:10,distance_km:1,fatalities:null}),f(3,{ef_rating:null,event_date:null,path_length_km:null,distance_km:null,fatalities:2}),f(4,{ef_rating:'1',event_date:'1950-01-03',path_length_km:20,distance_km:3,fatalities:1})]
assert.equal(display.nameFeatures(records)[0].properties.displayName,'EF3 — Kansas B')
assert.equal(display.nameFeatures(records)[1].properties.displayName,'EF3 — Kansas A')
assert.equal(display.nameFeatures([f(9,{ef_rating:2})])[0].properties.displayName,'EF2 Tornado')
assert.equal(display.normalizePlace('dallas, tx'),'Dallas, TX')
assert.equal(display.eventDate({id:1,event_id:'19730925'}),null)
assert.equal(display.eventDate({id:1,event_date:'2023-02-29'}),null)
assert(!display.stormSummary(records[1].properties).includes('fatalit'))
assert(display.stormSummary(records[0].properties).includes('Kansas'))
assert.deepEqual(state.filterEvents(records,[3], '', '',1972),[])
assert.deepEqual(state.filterEvents(records,[-1,1], '', '',1950).map(f=>f.properties.id),[3,4])
assert.deepEqual(state.sortEvents(records,'nearest').map(f=>f.properties.id),[1,2,4,3])
assert.deepEqual(state.sortEvents(records,'deadliest').map(f=>f.properties.id),[3,4,2,1])
assert.deepEqual(state.sortEvents(records,'strongest').map(f=>f.properties.id),[1,2,4,3])
assert.deepEqual(state.sortEvents(records,'longest').map(f=>f.properties.id),[4,1,2,3])
assert.deepEqual(state.sortEvents(records,'recent').map(f=>f.properties.id),[1,2,4,3])
const shared=state.parseState('?place=Dallas%2C+TX&lat=32.7&lon=-96.8&radius=80&year=1973&ef=3,4&sort=strongest&tornado=42&from=1950')
assert.deepEqual(state.parseState(state.stateQuery(shared)),shared)
assert.equal(state.parseState('?radius=-3&lat=NaN&sort=garbage&tornado=bad').radius,50)
assert.deepEqual(state.parseState('?ef=').ef,[])
assert.equal(state.stateQuery(state.parseState('')),'')
assert.deepEqual(display.toFeatures([{id:1,geom:JSON.stringify({type:'LineString',coordinates:[[-97,33],[0,0]]})}])[0].geometry.coordinates,[[-97,33],[-97,33]])
console.log('20 explorer assertions passed: real-data naming, missing values, date validation, composed filtering, all sorts, URL validation/round-trip, invalid endpoints.')

assert.deepEqual(state.parseState('?ef=garbage').ef,state.allRatings)
const { enrichRecords } = require('../src/lib/sourceMetadata.ts')
enrichRecords([{id:1,ef_rating:'1',event_date:'1950-10-01',path_length_km:15.8,path_width_m:10,fatalities:0,injuries:0,start_lon:-102.52,start_lat:36.73,end_lon:-102.3,end_lat:36.88}, {id:2,ef_rating:'5',path_length_km:15,start_lon:0,start_lat:1,end_lon:0,end_lat:2}]).then(([matched,missing])=>{
 assert.equal(matched.state,'OK');assert.equal(matched.path_length_km,15.8*1.609344);assert.equal(missing.state,null);assert.equal(missing.path_length_km,null)
 console.log('5 additional assertions passed: invalid EF URL fallback, real CSV metadata/unit conversion, and unmatched-record handling.')
}).catch(e=>{console.error(e);process.exitCode=1})
